FROM mysql/mysql-server:5.7.22

# COPY schema/config.sql /data/config.sql
# WORKDIR /data
# ARG MYSQL_USER
# ARG MYSQL_PASSWORD
# ARG MYSQL_ROOT_PASSWORD

# RUN echo "test" > /data/test
# RUN echo $MYSQL_PASSWORD > /data/psswd
# RUN echo $MYSQL_ROOT_PASSWORD > /data/rootpsswd
# RUN echo $MYSQL_DATABASE > /data/db

# RUN sleep 15 && mysql -u root -p $MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $MYSQL_DATABASE;"
# && \
# 	mysql -u root -p $MYSQL_ROOT_PASSWORD $MYSQL_DATABASE < /data/config.sql && \
# 	mysql -u $MYSQL_USER $MYSQL_PASSWORD $MYSQL_DATABASE < /data/createTables.sql